general.live_config_reload = true
general.import = [
  # "~/.config/alacritty/one-dark-theme.toml",
  "~/.config/alacritty/tokyo-night.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[font.italic]
family = "Fira Code"
style = "italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[font.offset]
x = 0
y = 1

[scrolling]
history = 10000
multiplier = 3

[terminal]
osc52 = "CopyPaste"

[terminal.shell]
program = "/usr/bin/zsh"
args = ["--login"]

[window]
decorations = "none"
opacity = 0.99

[window.dimensions]
columns = 1330
lines = 840

[window.padding]
x = 0
y = 0

[cursor.style]
shape                 = "Beam"
# blinking              = "Always"

[colors.cursor]
text                  = "#1E1E2E"
cursor                = "#61afef"

[cursor]
# thickness = 0.10
blink_interval        = 500
blink_timeout         = 0
